# the base URL of your notes Github pages website
base_url: https://toff63.github.io/notepad/

# the URL of your notes Github repo
repo_url: https://github.com/toff63/notepad

# the name for your notes website
name: Notepad

# the description of the notes website
description: Technical notes to ease my life :)
